# Python Basics

The goal of this notebook is to provide students with knowledge of the fundamentals of python. We will take a more interactive approach than most class room settings and ask the students to do some research on their own then bring their learnings back here to share with the class. 

### Variables

Variables work by assigning a value to a specific word or string of characters. It can be done using the "=" sign. This assigns whatever is on the right the string of characters on the left. We'll go ahead and try assigning a few variables in the next block.

In [2]:
a = 1
b = 2
c = 3
c # when you put a variable by itself, its value will be printed (This is a comment - anything after a # on the same line will be ignored)

3

We can also perform basic algebra to these variables and save the output to a new variable

In [3]:
d = a + b
d

3

In [4]:
e = c - a
e

2

In [5]:
f = b * c
f

6

In [6]:
g = a / b
g

0.5

Sometimes we want to update the value of one variable, so we can do this

In [7]:
g = g*2 # the same thing works for /, +, and -
g

1.0

This can get quite annoying with longer variable names, so we can do the following

In [8]:
f/=2 # there is also +=, -=, and *=
f

3.0

There are tons of different types of variables we can make. For this next section, we will ask the students to go out and figure out how to create the following types of variable: strings, floats and booleans. Once you have created these variables, try the same operations we used above and see what they do.

Create a few string variables here, then try to add them together, subtract them, multiply them and divide them to see what happens. You may get an error, and thats okay. Its important to know what can and can't be done with a type of data.

In [9]:
mystring = 'Hi'
mystring1 = 'bye'
mystring2 = mystring + mystring1
mystring2

'Hibye'

Create a few float variables here, then try to add them together, subtract them, multiply them and divide them to see what happens. You may get an error, and thats okay. Its important to know what can and can't be done with a type of data.

In [10]:
myfloat = float(7)
myfloat

7.0

Create a few boolean variables here, then try to add them together, subtract them, multiply them and divide them to see what happens. You may get an error, and thats okay. Its important to know what can and can't be done with a type of data.



In [11]:
d = True
d = False
d

False

### Lists, Dictionaries, and Tuples



Lists work similarly to the variables we created above but store multiple values. We'll cover the types metioned above then ask the students to try and create their own versions of them.


First up, lists. you can create a list with the following code.

In [12]:
my_list = [1, 2, 3, 4, 5]

To access a specific item from the list, you would do the following.

In [13]:
my_list[2] # here, 2 is the index you are accessing

3

The first element in the list is at index 0, then the second element is at index 1 and so on.



In [14]:
print(my_list[0], my_list[1], my_list[2], my_list[3], my_list[4])

1 2 3 4 5


**TODO:** Below, create a list of your favorite colors. Then figure out how to add a new element to the end of the list. Finally change a value in the list to something new.


In [15]:
colors = [blue, red, green, purple, indigo]

NameError: name 'blue' is not defined

Now, figure out how to `append` a new element to the end of the list. Maybe google "how to append an element to a list python"

Finally change a value in the list to something new.



In [16]:
colors = ['blue', 'red', 'green', 'purple', 'indigo']
colors.append('yellow')
colors

['blue', 'red', 'green', 'purple', 'indigo', 'yellow']

### For loops, while loops, and if statements 



We will learn more about for loops in the next lesson. For now, we will use them to go through a list and print out each element.

In [1]:
for number in my_list:
  print(number)

NameError: name 'my_list' is not defined

Next, we will look at how to make a list run a specific number of times.

In [17]:
for i in range(5): # range functions the same here as the list [0,1,2,3,4,5]
    print('i = ', i)

i =  0
i =  1
i =  2
i =  3
i =  4


Next, we'll take a look at while loops. In general, you can make a while loop do anything that a for loop can do but with slightly different syntax, so if you find youself understanding while loops better than for loops, you can just focus on using while loops. 

In the block below, we will make a while loop that runs 5 times. For while loops, we can't specify how long they will run for ahead of time so its important for us to create an achievable exit condition. An exit condition is just the condition that will cause the code to stop running. This is checked every time, immediatly before the code runs or reruns. We want to make sure that this condition will eventually happen, otherwise the code will run until something crashes or we manually close it

In [18]:
i = 0
while i < 5:
    print("Hello World")
    i = i + 1

Hello World
Hello World
Hello World
Hello World
Hello World


Now for if statements. The if-elif-else statement is used to conditionally execute a statement or a block of statements. Conditions can be true or false, execute one thing when the condition is true, something else when the condition is false.

In [19]:
a = 1
b = 2
if a > b:
    print("a is greater than b")
else:
    print("b is greater than a")

b is greater than a


We can add else statements to the above. An else statement is what will be run if the original statement is false.

In [20]:
a = 1
b = 2
if a > b:
    print("a is greater than b")
else:
    print("b is less than a")

b is less than a


Additionally, we can use elif statements to add additional conditions to the structure.

In [21]:
a = 1
b = 1
if a > b:
    print("a is greater than b")
elif a == b:
    print("a equals b")
else:
    print("b is less than a")

a equals b


Now its your turn. Either break up into 3 teams and have each team solve one of the blocks or solve them all together.

In the next block, create a for loop that counts from 0 to 10 and prints out each number. Additionally, if the number is less than 3, print out "This is a small number".

In [22]:
i = 0
while i < 11:
    print(i)
    i = i + 1
    if i < 4:
        print("This is a small number")

0
This is a small number
1
This is a small number
2
This is a small number
3
4
5
6
7
8
9
10


In the next block, create a while loop that prints out all of the even numbers between 1 and 10. Additionally, if the number is between 5 and 9, print the number out a second time.



In [23]:
i = 0
while i < 11:
    print(i)
    i = i + 1
# for i in range(0, 11, 2):
#     print(i)

0
1
2
3
4
5
6
7
8
9
10


In the next block, ask the user to input 3 items and add them all to a list. Then. create a loop that prints out each item that the user entered.



### Functions

Functions act like variables but instead of storing a value, they store lines of code. Below we can see how a function is created and used.

In [24]:
def my_first_function():
    print('Hello world')

In [25]:
my_first_function()

Hello world


Whenever the computer sees the function being used, it automatically runs the code stored inside of that function.

Additionally, functions can take in one or multiple values to use in their code, as we can see below.

In [26]:
def add_numbers(a, b, c):
    total = a + b + c
    print(total)

In [27]:
add_numbers(1, 2, 3)

6


Finnally, functions can have a "return" statement. This is what the function sends back to the place it was called. You can think of functions like black boxes where the parameters in the parentheses are the input and the return statement is the output. This output can be saved to a variable to be used later. We will redefine the add_numbers function from above using a return statement to show this off.

In [28]:
def add_numbers(a, b, c):
    total = a + b + c
    return total

In [29]:
out = add_numbers(1, 2, 3)
out

6

Now its your turn! You can either work on each of the following challenges in teams of 2 or walk through each one as a group. In any case, it is recommended to look at them at a high level together so that everyone understands the concepts in each section.

In the block below, create a function that takes in 2 numbers and returns True if the product of the numbers is positive and False in all other cases.

In the block below, create a function that takes in a string and returns the string in reverse order. For example, if the input was "Hello" the output should be "olleH"

In the block below, create a function that takes in a list and prints out each element 1 at a time. For example, if the input was ['Dog', 'Cat', 'Hamster'], the output should be

Dog

Cat

Hamster

### Modules (Numpy and OpenCV)

In the following section we will be covering modules. Above, we leaned about functions and the power that they have. Modules let us use functions that other people have created to solve problems that we commonly incounter. For example, if we find that we frequently have to get a random number, instead of coding it every time, you could just import a function that either you or someone else created in the past. Basically, modules and importing lets us have access to the work of many other coders, making it a very powerful tool.

Below, we will import the numpy module and use a few of its functions to show off this power

Here, we rename it to np to make it more easily accessable

In [30]:
import numpy as np

Numpy is a library which is coded outside of python, making it faster. It gives us access to better and more efficient lists

With it, we can make a list like this:

In [31]:
my_array = np.zeros((2,3)) # (2,3) is the shape of the array
my_array

array([[0., 0., 0.],
       [0., 0., 0.]])

or like this:

In [32]:
np.random.rand(3,2) # we don't need to put the shape in braces this time

array([[0.96766373, 0.00699307],
       [0.46163139, 0.22647583],
       [0.42639761, 0.82892049]])

Just like regular variables, we can do opperations on this list

In [33]:
my_array2 = my_array + 1
my_array3 = my_array2 * 2
my_array2, my_array3

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2., 2., 2.],
        [2., 2., 2.]]))

Make an array from my_array of all -3s:



Now, it's time to explore some computer vision with OpenCv! First, we will need to import the necessary packages!

In [34]:
import cv2
from skimage import io
from google.colab.patches import cv2_imshow

ModuleNotFoundError: No module named 'cv2'

First, we want to get the url of a particular image

In [35]:
url = "https://www.akc.org/wp-content/uploads/2017/11/GettyImages-187066830.jpg"

Next, we want to read the picture from the url and turn it into BGR format

In [36]:
img = cv2.cvtColor(io.imread(url), cv2.COLOR_RGB2BGR)
cv2_imshow(img)

NameError: name 'cv2' is not defined

Our image is a little too large, let's resize it!

In [37]:
img = cv2.resize(img, (180, 180))
cv2_imshow(img)

NameError: name 'cv2' is not defined

Now, let's try to cast an image to only blue! cv2.split splits an image to 3 channels of pattern: blue, green, red

In [38]:
b, g, r = cv2.split(img)
# fill other non-blue channels with zeros to achieve all blues
zeros_ch = np.zeros(img.shape[0:2], dtype="uint8")
blue_img = cv2.merge([b, zeros_ch, zeros_ch])
cv2_imshow(blue_img)

NameError: name 'cv2' is not defined

Finally, let's try and rotate this image!

In [39]:
cv2_imshow(blue_img)
cv2_imshow(cv2.rotate(blue_img, 0)) # rotate clockwise 90 degrees

NameError: name 'cv2_imshow' is not defined

Below, find your own image, display it, resize it to your choosing, make the image only green or red, and then rotate it!

If you are coding this on your own, you may need to install packages like numpy or OpenCV, which we will get into later, but there are many built in packages as well



time allows us to access the current time

In [40]:
import time
time.time() # you will see this go up as you rerun it

1656432003.3551204

random allows us to get random numbers

In [41]:
import random
random.randint(0,5) # this gives one of the numbers between and including 0 and 5

1

Find a built in module and use it here:

In [42]:
import 

SyntaxError: invalid syntax (2125240012.py, line 1)

You may notice that we have to call the function we need by placing it after the module connected by a dot

But many times, that is inconvenient and we can get around it like this

In [43]:
from random import randint
randint(0,5) # now we can exclude the random. prefix

3

finally, as we did with the numpy module, we can rename the function

In [44]:
from time import time as t
t()

1656432003.4212499